description: "A new Flutter application."
name: "flutterapp"
publish_to: "none"
version: "1.0.0+1"
dependencies: 
  cupertino_icons: "^0.1.3"
  path_drawing: "^0.4.1"
  flutter: 
    sdk: "flutter"
dev_dependencies: 
  flutter_test: 
    sdk: "flutter"
environment: 
  sdk: ">=2.7.0 <3.0.0"
flutter: 
  assets: 
    - "assets/images/"
  fonts: 
    - 
      family: "Roboto"
      fonts: 
        - 
          asset: "fonts/Roboto-regular.ttf"
          style: "normal"
          weight: 400
    - 
      family: "Rhodium Libre"
      fonts: 
        - 
          asset: "fonts/RhodiumLibre-regular.ttf"
          style: "normal"
          weight: 400
    - 
      family: "Red Rose"
      fonts: 
        - 
          asset: "fonts/RedRose-regular.ttf"
          style: "normal"
          weight: 400
    - 
      family: "Puritan"
      fonts: 
        - 
          asset: "fonts/Puritan-700.ttf"
          style: "normal"
          weight: 700
        - 
          asset: "fonts/Puritan-italic.ttf"
          style: "italic"
          weight: 400
        - 
          asset: "fonts/Puritan-regular.ttf"
          style: "normal"
          weight: 400
  uses-material-design: true
